### ISSUE TITLE
Scaffolding error w/ CASCADE referential action

### ISSUE THREAD

**Issue by mguinness** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#127]
### Steps to reproduce
A table definition that includes a referential action constraint will produce error "Sequence contains no matching element".

```
CONSTRAINT `FK_AspNetRoleClaims_AspNetRoles_RoleId` FOREIGN KEY (`RoleId`) REFERENCES `AspNetRoles` (`Id`) ON DELETE CASCADE
```

### The issue

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.GetIndexes()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GetMetadataModel(ReverseEngineeringConfiguration configuration)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GenerateAsync(ReverseEngineeringConfiguration configuration, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

MySQL version: 5.6.27-log
Operating system: Linux
Pomelo.EntityFrameworkCore.MySql version: 1.1.0-rtm-10008

**Comment by Kagamine** [comment]
I will investigate and fix this later today.

**Comment by Kagamine** [comment]
Fixed in 10010

**Comment by mguinness** [comment]
Getting the following error which is caused by table having UNIQUE INDEX:

```
System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.
   at MySql.Data.MySqlClient.MySqlDataReader.GetString(Int32 ordinal)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.GetConstraints()
```

Looking at the code a quick fix would be to replace `CONSTRAINT_NAME <> 'PRIMARY'` with `REFERENCED_TABLE_NAME IS NOT NULL` in GetConstraintsQuery.

Otherwise you could use `CONSTRAINT_TYPE = 'FOREIGN KEY'` in INFORMATION_SCHEMA.TABLE_CONSTRAINTS table.

On a side note, is there a reason why tinytext, text, mediumtext, longtext data types are mapped to byte[] and not string?

**Comment by Kagamine** [comment]
Shipped in 1.1.0-rtm-10011

**Comment by mguinness** [comment]
@Kagamine It appears you inadvertently truncated the SQL in GetConstraintsQuery:

should read
`AND REFERENCED_TABLE_NAME IS NOT NULL`
instead of
`AND REFERENCED_TABLE_NAME IS NOT NUL`

**Comment by mguinness** [comment]
@Kagamine Still not working quite right, but nearly there.

Maybe revert `AND CONSTRAINT_TYPE = 'FOREIGN KEY'` back to `AND CONSTRAINT_NAME <> 'PRIMARY'` in GetConstraintsQuery.

Also there's an issue with indexes containing several fields.  Suggest you use the following for GetIndexesQuery instead:

```
SELECT NON_UNIQUE, INDEX_NAME, GROUP_CONCAT(`COLUMN_NAME` SEPARATOR ', ') AS COLUMNS
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = '{0}'
AND TABLE_NAME = '{1}'
AND INDEX_NAME <> 'PRIMARY'
ORDER BY SEQ_IN_INDEX;
```

**Comment by mguinness** [comment]
I also noticed an issue with scaffolding if table PK data type is `MEDIUMINT(9)`, but works if `INT(9)`.

```
CREATE TABLE test (
	id MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id)
);
```

**Comment by Kagamine** [comment]
Could you open a PR to help us improve this behavior?

**Comment by mguinness** [comment]
Sure, see PR https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/130
