### ISSUE TITLE
.Average() Query is Breaking

### ISSUE THREAD

**Issue by munir-jb** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#385]
Hello guys, I'm running EF .Average() query normally in 2.0.0-rtm-10056, and suddenly at 2.0.0 it's breaking with these error message : unable to cast object of type "system.decimal" to type "system.double".

Any person had the same problem? because it's breaking on all of my average() code, not just in particular location.

the database field already defined as double, the EF field class has double type too, and the variabel to read the output is also defined in double.

**Comment by mguinness** [comment]
My guess it's related to changes in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/374 which should've been included in 2.0.0-rtm-10058 a couple weeks back.

**Comment by Kagamine** [comment]
@mguinness , @caleblloyd Did we fixed this bug?

**Comment by mguinness** [comment]
@munir-jb Can you retest using build [10071](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.0.1-preview-10071) as there have been several changes in the past month.

**Comment by caleblloyd** [comment]
@munir-jb please provide an example of the query you are running in EF

**Comment by munir-jb** [comment]
Until this morning I'm still using <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.0.0-rtm-10056" /> which working perfecly for my needs.

I'll try using newer version now. Will be post the result soon.

**Comment by munir-jb** [comment]
![image](https://user-images.githubusercontent.com/14286629/31926950-014b1a7c-b8bc-11e7-91e4-fd2db0ffb407.png)

still the same issue.
details :
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidOperationException: An exception occurred while reading a database value. The expected type was 'System.Double' but the actual value was of type 'System.Decimal'. ---> System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Double'.
   at MySql.Data.MySqlClient.Results.Row.GetDouble(Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Average(IQueryable`1 source)
   at GLSDashboardCore.Controllers.DashboardController.GetAllDataPenilaian(String level, String jenis_detil_penilaian, String tahun_ajaran_penilaian, String level_chart, String jenis_penilaian, String NPSN, Int32 id_kelas) in D:\GIT\GLSDashboardCore\GLSDashboardCore\GLSDashboardCore\Features\Dashboard\DashboardController.cs:line 797

the query where constructed like this :
`						var query_average_nilai = (from f_nilai in _context.f_nilai
																			 from waktu in _context.d_waktu
																			 where f_nilai.kode_waktu == waktu.kode_waktu && waktu.kode_waktu == tahun_semester && f_nilai.jenis_penilaian == list_jenis_penilaian[a].ToString()
																			 select f_nilai.nilai_angka).Average();`

**Comment by mortenbirkelund** [comment]
Anything new on this? I am experiencing the same error using 
`    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.0.1" />`

**Comment by mguinness** [comment]
@mortenbirkelund Can you share a repo with the recreate that can be cloned and run?

**Comment by mortenbirkelund** [comment]
I will try, but for now it just seems easier to manually calculate the average by sum / count

**Comment by caleblloyd** [comment]
Please try upgrading to 2.1.1 and open a new issue if the problem persists

**Comment by munir-jb** [comment]
continued at #644
